### ISSUE TITLE
Top bar doesn't hide after disconnecting from secondary display

### ISSUE THREAD

**Issue by kevincianfarini** [tuxor1337/hidetopbar#154]
Gnome Version: 3.26
Display Manager: Wayland
OS: Fedora 27

As soon as I disconnect from a secondary monitor, the top bar doesn't disappear any more. For this functionality to resume, I need to log out and back in or lock the screen and unlock it.

**Comment by kevincianfarini** [comment]
This issue is still present on 3.30.2 and Fedora 29. I have noticed that normal functionality can be resumed when locking and unlocking the screen. Also present on Xorg.

**Comment by s0kil** [comment]
I have the same issues on POP_OS 19.04

**Comment by meddario** [comment]
Hi, i can confirm that the same issue happens on Ubuntu 18.04 with Gnome 3.28.2.
Settings:
![hide-top-bar-settings](https://user-images.githubusercontent.com/16596646/69900152-5c0f6880-1370-11ea-8931-13ced7e2945f.png)

**Comment by stecenator** [comment]
Hi!
It just hit me on Fedora 33. When I use HDMI it's ok, but with USB-C I need to disable an re-enable the extension.

**Comment by tuxor1337** [comment]
Closing as duplicate of #360
