### ISSUE TITLE
GNOME 41: Overview search bar collapses

### ISSUE THREAD

**Issue by jesusferm** [tuxor1337/hidetopbar#321]
On gnome 41 disappear text box search on active extensions

https://imgur.com/NjngK9o

**Comment by rakshitraj** [comment]
Refer duplicate issue #329

**Comment by shemgp** [comment]
This issue still appears in gnome-shell 42.alpha when Dash-to-Dock is enabled as well. Dash-to-Dock adds a small preview of workspaces so it pushes the search bar to make it small.

Here's a screenshot without dash-to-dock:
![Screenshot from 2022-02-04 16-09-20](https://user-images.githubusercontent.com/1734126/152494853-bec10748-4892-476e-a13f-3d5d4c675950.png)

Here's the screenshot with dash-to-dock enabled:
![Screenshot from 2022-02-04 16-09-30](https://user-images.githubusercontent.com/1734126/152494887-7abac1a5-912f-49b4-96f1-07da1f7420eb.png)

The temporary resolution in: https://github.com/mlutfy/hidetopbar/issues/321#issuecomment-952843347 works.

**Comment by shemgp** [comment]
Sorry, I forgot. Here's the screenshot of hide-top-bar disabled and dash-to-dock enabled:
![Screenshot from 2022-02-04 16-23-05](https://user-images.githubusercontent.com/1734126/152495846-8473012e-4264-4f47-96ce-2bf03b6ddc28.png)

As you can see even if the top bar is shown and dash to dock is enabled, the search entry is not squished.

**Comment by paddylandau** [comment]
I confirm that I get this same problem. I created a fresh installation of Ubuntu 22.04, and installed Hide Top Bar (there are no other extensions except the ones that come by default).

When "Show panel in overview" is turned off, the search bar is correct.

![Show panel in overview is turned off](https://gcdnb.pbrd.co/images/V71fd7lMkBJc.png)

When "Show panel in overview" is turned on, the search bar is too thin.

![Show panel in overview is turned on](https://gcdnb.pbrd.co/images/ZbiAZcd06rTH.png)

Thank you

**Comment by v-tibi** [comment]
Happens on Gnome 43 as well.

**Comment by igor2x** [comment]
Tested on Ubuntu 22.10 on Gnome 43.0 and I can happily confirm this problem is now fixed. Thanks a lot for fixing the problem.

**Comment by paddylandau** [comment]
> Tested on Ubuntu 22.10 on Gnome 43.0 and I can happily confirm this problem is now fixed. Thanks a lot for fixing the problem.

Also fixed on 22.04, though I had to restart the computer before it worked properly.
