### ISSUE TITLE
GNOME 42: Top panel stuck open

### ISSUE THREAD

**Issue by jdoe0000000** [tuxor1337/hidetopbar#354]
If the cursor leaves the panel without immediately touching the desktop (e.g. it could go directly on top of an overlapping window), the `leave-event` signal doesn't fire and the panel will be stuck.

https://user-images.githubusercontent.com/67334567/159691713-a9dbd294-2b89-4924-8e70-279f81527ca5.mp4

**Comment by tuxor1337** [comment]
Thanks for reporting this! It's indeed weird and must have to do with changes in GNOME 42 since it's not present with GNOME 40.

**Comment by jacksongoode** [comment]
Same issue!

**Comment by MateusMolina** [comment]
Having the same issue on Fedora 36, Wayland and Shell 42. No other extensions installed.

**Comment by CO-1** [comment]
Recompiling mutter from source with changes from https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321 fixes the problem

**Comment by PHLAK** [comment]
> Recompiling mutter from source with changes ... fixes the problem

Does this mean the problem will resolve itself if/when my mutter is updated (with these changes)?
