### ISSUE TITLE
Move the extension repo?

### ISSUE THREAD

**Issue by mlutfy** [tuxor1337/hidetopbar#373]
Hi @tuxor1337, I was wondering if it would be OK for me to move this repo under your github account? You have been maintaining this extension for such a long time, I think it would make more sense.

If I recall correctly, Github will add a redirect, so it will not break forks / links / etc.

Thank you for all the work you do on this extension. I still use it, and am a happy user :)

(sorry I would have sent an email, but could not find it)

**Comment by tuxor1337** [comment]
Hi @mlutfy, 

Thanks for your message! Sorry for the late reply, I just returned today from an "off-grid" vacation :)

Yes, feel free to move this repo under my GitHub account. And I agree: This should result in a simple redirect from the old to the new URL. 

Best,
Thomas

**Comment by mlutfy** [comment]
Request sent. Thanks!

**Comment by tuxor1337** [comment]
Thanks, all redirects work as expected!
