### ISSUE TITLE
Uncompatible with Gnome version 42.2

### ISSUE THREAD

**Issue by PinkMoon25** [tuxor1337/hidetopbar#380]
I just wanted to know if there is any option to use it on Ubuntu 22.04.1 LTS. I really like this extension but I can not seem to use it after updating to Ubuntu 22.04.1 LTS, I get the error in Gnome extension which says "The extension is incompatible with the current GNOME version"

**Comment by coldtobi** [comment]
(See #377.)
No idea  how you have installed it, if you did using apt, you need to remove it and then install it using https://extensions.gnome.org/extension/545/hide-top-bar/

**Comment by PinkMoon25** [comment]
> You might want to create an issue ticket in Ubuntu to make them aware -- when I talked to them about this a few days, they were like "noonoe complained, so it we guess it is fine".

Alright Thanks, I will try to raise the complaint there then :+1:
