### ISSUE TITLE
How to update or disable update notifications?

### ISSUE THREAD

**Issue by stax76** [tuxor1337/hidetopbar#381]
I'm on Ubuntu 22.04.

Quite often I get notifications that the extension can be updated, it's very disruptive.

I tried to update it over the web interface and there it showed an error.

The web interface also shows there is an issue:
Your native host connector do not support following APIs: v6

I googled this and somebody wrote that this is OK and will not cause a problem in Ubuntu 22.04

I also had problems installing this extension, maybe I didn't install it in a way it can be updated easily, how I installed it is described here:

https://github.com/tuxor1337/hidetopbar/issues/377#issuecomment-1232616738

**Comment by stax76** [comment]
Maybe the update did work, in the settings it said I need to log out.

**Comment by tuxor1337** [comment]
The notifications about updates are not generated from our end. Please file an issue with GNOME or with Ubuntu, if you would like to see an improvement on that.
