### ISSUE TITLE
Three-fingers down gesture unhides top panel but it is transparent and overlaps with window title, sometimes getting stuck

### ISSUE THREAD

**Issue by eyrent** [tuxor1337/hidetopbar#384]
### Bug summary (copy of gnome-shell but report)

**System details**
- Fedora Workstation 36
- GNOME 42.4
- Kernel 5.19.4-200.fc36.x86_64
- Wayland

I'm using the [Hide Top Bar](https://extensions.gnome.org/extension/545/hide-top-bar/) extension, latest version for my distro (Fedora 36). Therefore my top panel is hidden unless I hit the top limit of my screen or opening overview. I recently discover that if I do the three-finger gesture down in my touchpad it 'peeks' the bar until I let go. However there's no back background when I do this and thus interferes with the window titles behind as shown in the picture above. 

While getting the screenshot the top bar freezed in that state and I had to use the gesture again to unlock it. Also when the bar is sliding back to the hidden state I can see briefly the dark background it was supposed to have.

**Issues related**

Though, this belongs to another bug report (probably to the extension developers), when I have an app with no system titlebar (own style or different like VSCode's or Firefox's) the bar refuses to unhide (you can see it do it and immediately hide again). Perhaps this two issues are related. 

I hope I'm reporting this bug in the correct place. If not, my apologies. Thanks

### Steps to reproduce

1. Fresh install of Fedora 36
2. Install [Hide Top Bar](https://extensions.gnome.org/extension/545/hide-top-bar/) shell extension.
3. Place three fingers in the touch pad and drag them down.
4. Release

### What happened

Top bar unhides but has no black background so it overlaps the underlying window title (maximized) rendering the information unreadable. When releasing the three-finger gesture, you can see very briefly the background appear suddenly as the bar hides back again.

### What did you expect to happen

Top bar should reveal as long as the gesture is hold with a proper background (as usual)

### Relevant logs, screenshots, screencasts etc.

While holding gesture
![While holding gesture](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/8fec22ffc857db9b9fe7d701ee47f5e6/image.png)
Just released
![Just released](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/7ca94542dc639f65b29835404c331b89/image.png)
Hide Top Bar settings
![Hide Top Bar settings 1](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/f57216222c518ca8c9ffa183add9c8f8/image.png)
![Hide Top Bar settings 2](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/3b6395f93e236a0e42d925768d373e35/image.png)
![Hide Top Bar settings 3](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/a076d3e484ea496cec919d461972b38f/image.png)
![Hide Top Bar settings 4](https://gitlab.gnome.org/GNOME/gnome-shell/uploads/065686dd9ea7b7ad1c86f05b0d97768f/image.png)

**Comment by tuxor1337** [comment]
Thanks for the detailed report!

The behavior you describe has already been reported here: #372
