### ISSUE TITLE
"gnome-shell --replace &" does not work on Wayland? Suggestion: add a comment to indicate this?

### ISSUE THREAD

**Issue by stephane-klein** [tuxor1337/hidetopbar#398]
[Here](https://github.com/tuxor1337/hidetopbar/blob/master/README.md?plain=1#L48) I read:

```
    gnome-shell --replace &
```

but when I execute this command I have:

```
$ gnome-shell --replace &
[1] 15444
libmutter-Message: 19:32:03.872: Running GNOME Shell (using mutter 43.2) as a Wayland display server
Failed to setup: Could not take control: GDBus.Error:System.Error.EBUSY: Device or resource busy[1]  + 15444 exit 1     gnome-shell --replace
```

I run on Wayland environment, maybe this command is limited to X11?

I yes, what do you think that I create a merge request to add a comment to say this command does not work on Wayland?

Best regards,  
Stéphane

**Comment by tuxor1337** [comment]
Thanks, well spotted! I added a comment about this to the README :)
